#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing prerequisites]${normal}"
sudo apt-get -y install acl glusterfs-server lvm2 rpcbind thin-provisioning-tools xfsprogs
echo ": sudo apt-get install acl glusterfs-server lvm2 rpcbind thin-provisioning-tools xfsprogs" >> ~/.zsh_history

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating .pkglist]${normal}"
comm -12 <(grep 'sudo apt-get install' ~/.zsh_history | sed '/|/d' | awk '{$1=$2=$3=$4=""; print $0}' | sed s/\\s/\\n/g | sort -n) <(dpkg --list | awk '{print $2}' | sed 's/:armhf//' | sort -n) | sed '/^$/d' > ~/.pkglist

echo ""
echo "${bold}[CONFIGURING]${normal}"
echo "${bold}[Configuring GLUSTERD SERVICE]${normal}"
sudo systemctl enable --now glusterd.service

echo ""
echo "${bold}[GLUSTERFS]${normal}"
echo "${bold}[Formatting filesystem]${normal}"
sudo dd if=/dev/zero of=/dev/sda bs=512 count=1
sudo pvcreate /dev/sda
sudo vgcreate gluster /dev/sda
sudo lvcreate --thin gluster/brick --extents 100%FREE --poolmetadatasize 16GB --zero n
sudo mkfs.xfs -f -i size=512 -n size=8192 /dev/gluster/brick
echo "${bold}[Mounting filesystem]${normal}"
sudo mkdir /mnt/gluster
sudo cp /etc/fstab /etc/fstab.bak
cp /etc/fstab /tmp/fstab
echo "/dev/gluster/brick /mnt/gluster xfs rw,inode64,noatime,nouuid 0 2" >> /tmp/fstab
sudo mv /tmp/fstab /etc/fstab
sudo mount -av

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review critical services]${normal}"
systemctl --type=service | grep 'glusterd\|lvm2-monitor\|rpcbind\|smartd'
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review fstab]${normal}"
cat /etc/fstab

echo ""
echo "${bold}[Review mounts]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[Mounts]") <(lsblk) <(echo "") <(echo "[Usage]") <(df -h) | less
echo "${bold}[Review LVM]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[Physical volumes]") <(sudo pvdisplay) <(echo "[Volume groups]") <(sudo vgdisplay) <(echo "[Logical volumes]") <(sudo lvdisplay) <(echo "[Metadata]") <(sudo lvs -o+metadata_percent) | less

echo ""
echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart

echo ""
echo "${bold}[DONE]${normal}"
