#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get -y dist-upgrade

echo ""
echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing prerequisites]${normal}"
sudo apt-get -y install git zsh
echo "${bold}[Installing oh-my-zsh]${normal}"
yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sudo chsh --shell /usr/bin/zsh $USER

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review shell]${normal}"
awk -F: -v user="$USER" '$1 == user {print $NF}' /etc/passwd

echo ""
echo "${bold}[DONE]${normal}"
zsh
